### ISSUE TITLE
Installation error on moodle that runs on docker

### ISSUE THREAD

**Issue by jeanmaack** [SE-Stuttgart/moodle-block_booksearch#2] opened 2023-04-19 11:27 UTC
Hey there. When uploading the zip file to my moodle plugin installer, it throws the following error:

![image](https://user-images.githubusercontent.com/131260758/233061011-052fcc1d-ab02-4e58-9d29-34827a757805.png)

Can you help me fix this?

**Comment by kasrahabib** [comment] 2023-06-04 14:13
Hello @jeanmaack 

Thank you for bringing this to our attention. We have identified the cause of the problem: the .git file was mistakenly included in the repository.

We have addressed this issue and made the necessary changes. Kindly let us know if the problem has been resolved, and we will proceed to close the issue.

Best,
Kasra

**Comment by coderDem** [comment] 2023-06-05 09:52
@kasrahabib thank you for the new version. We could install the plugin in Moodle. This issue can now be closed.

**Closed as completed** 2023-06-06 14:51 UTC
